---
- name: install prerequisites
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present

- name: Add docker repository
  yum_repository:
    name: docker-ce-stable
    description: docker-ce stable repository
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgkey: https://download.docker.com/linux/centos/gpg
    gpgcheck: yes

- name: install docker-ce
  yum:
    name: docker-ce
    state: present

- name: Make sure a service is running
  systemd:
    name: docker
    state: started
    enabled: yes
